Daves-MacBook-Pro-2:src daveti$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> url='http://www.5giay.vn'
>>> obj=urllib2.urlopen(url, timeout=20)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 441, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 280, in readheaders
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
KeyboardInterrupt
>>> 


# Normal case:

Daves-MacBook-Pro-2:Python-2.7.8 daveti$ ./python.exe
Python 2.7.8 (default, Nov 13 2014, 20:44:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> url='http://www.5giay.vn'
>>> obj=urllib2.urlopen(url, timeout=20)
daveti: req.timeout [20], host [www.5giay.vn]
daveti: socket readline
daveti: socket timeout in socket [20]
daveti: into sock_recv
daveti: start sock_recv_guts
daveti: socketmodule interval [20.000000]

daveti: socketmodule recv done
daveti: socketmodule timeout
daveti: done sock_recv_guts, outlen [-1], recvlen [8192]
('daveti: error to raise - ', timeout('timed out',))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 422, in _open
    '_open', req)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 1190, in do_open
    r = h.getresponse(buffering=True)
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 1076, in getresponse
    response.begin()
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 413, in begin
    version, status, reason = self._read_status()
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 369, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/Users/daveti/Python-2.7.8/Lib/socket.py", line 487, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out
>>> >>> 


# Latest issued trace

Daves-MacBook-Pro-2:Python-2.7.8 daveti$ ./python.exe
Python 2.7.8 (default, Nov 13 2014, 20:44:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> url='http://www.5giay.vn'
>>> obj=urllib2.urlopen(url, timeout=20)
daveti: req.timeout [20], host [www.5giay.vn]
daveti: socket readline
daveti: socket timeout in socket [20]
daveti: into sock_recv
daveti: start sock_recv_guts
daveti: socketmodule interval [20.000000]
daveti: socketmodule recv
daveti: recv outlen [404]
daveti: socketmodule recv done
daveti: socketmodule loop again
daveti: socketmodule loop end
daveti: final rtn [404]
daveti: done sock_recv_guts, outlen [404], recvlen [8192]
daveti: _sock.recv done
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: req.timeout [20], host [www.5giay.vn]
daveti: socket readline
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: httplib readheaders while True
daveti: socket readline
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: httplib readheaders while True
daveti: socket readline
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 422, in _open
    '_open', req)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 1190, in do_open
    r = h.getresponse(buffering=True)
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 1076, in getresponse
    response.begin()
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 447, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "/Users/daveti/Python-2.7.8/Lib/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "/Users/daveti/Python-2.7.8/Lib/rfc822.py", line 108, in __init__
    self.readheaders()
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 282, in readheaders
    line = self.fp.readline(_MAXLINE + 1)
  File "/Users/daveti/Python-2.7.8/Lib/socket.py", line 487, in readline
    data = self._sock.recv(self._rbufsize)
  File "/Users/daveti/Python-2.7.8/Lib/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/Users/daveti/Python-2.7.8/Lib/ssl.py", line 165, in read
    return self._sslobj.read(len)
KeyboardInterrupt
>>> ^D


# Fix!

Daves-MacBook-Pro-2:Python-2.7.8 daveti$ ./python.exe
Python 2.7.8 (default, Nov 13 2014, 20:44:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> url='http://www.5giay.vn'
>>> obj=urllib2.urlopen(url, timeout=20)
daveti: req.timeout [20], host [www.5giay.vn]
daveti: socket readline
daveti: socket timeout [20], timeout_due [1415953703.749258]
daveti: socket timeout in socket [20]
daveti: into sock_recv
daveti: start sock_recv_guts
daveti: socketmodule interval [20.000000]
daveti: socketmodule recv
daveti: recv outlen [404]
daveti: socketmodule recv done
daveti: socketmodule loop again
daveti: socketmodule loop end
daveti: final rtn [404]
daveti: done sock_recv_guts, outlen [404], recvlen [8192]
daveti: _sock.recv done
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: httplib readheaders while True
daveti: socket readline
daveti: req.timeout [20], host [www.5giay.vn]
daveti: socket readline
daveti: socket timeout [20], timeout_due [1415953704.300284]
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: httplib readheaders while True
daveti: socket readline
daveti: socket timeout [20], timeout_due [1415953721.140234]
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout in socket [20]
daveti: into SSLread
daveti: count [0]
daveti: no match for count [0]
daveti: normal return
daveti: _sock.recv done
daveti: socket timeout for recv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 422, in _open
    '_open', req)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/Users/daveti/Python-2.7.8/Lib/urllib2.py", line 1190, in do_open
    r = h.getresponse(buffering=True)
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 1092, in getresponse
    response.begin()
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 463, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "/Users/daveti/Python-2.7.8/Lib/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "/Users/daveti/Python-2.7.8/Lib/rfc822.py", line 108, in __init__
    self.readheaders()
  File "/Users/daveti/Python-2.7.8/Lib/httplib.py", line 292, in readheaders
    line = self.fp.readline(_MAXLINE + 1)
  File "/Users/daveti/Python-2.7.8/Lib/socket.py", line 513, in readline
    raise RuntimeError('socket readline/recv timeout')
RuntimeError: socket readline/recv timeout
>>> ^D
Daves-MacBook-Pro-2:Python-2.7.8 daveti$ 

